---
# DL Annotator
# Sample Startup Settings File for starting an annotation session (no initial GT data)
# For the user: Update this file with actual locations of annotation support files and folders before use of the tool!

# img_file_path: Location of the JPG images to be annotated
img_file_path: ./sample/traffic_imgs/

# gt_load_file_path: Path to be used for the input ground truth CSV file (reading in).  One row per Ground Truth Sample.  
# Use none if no GT data to start
gt_load_file_path: none

# gt_save_file_path: Path to be used for the output ground truth CSV file (writing out).  One row per Ground Truth Sample.
gt_save_file_path: ./sample/test_traffic.csv

# label_file_path: Path to text file containing the class labels for annotation.  One class label per line.
label_file_path: ./sample/coco_names.txt

# dnn_cfg_file_path: Path to Deep Neural Network config file - FUTURE FEATURE (WIP)
dnn_cfg_file_path: none

# dnn_model_file_path: Path to Deep Neural Network model (weights) file - FUTURE FEATURE (WIP)
dnn_model_file_path: none

# event_log_file_path: Path to store tool event logs.  Event log file names are autogenerated.
event_log_file_path: ./sample/event_logs
